### ISSUE TITLE
LogToPocketLogger fails on linux under heavy load

### ISSUE THREAD

**Issue by TyOverby** [jonsequitur/PocketLogger#57]
When using the `LogToPocketLogger` attribute on a test class, the file logger throws at the end of a test.

This happens very rarely, never when the single test is run manually, and only on tests that have large output.

```c#
[LogToPocketLogger(filename: "test.log")]
```

```
          <Message>System.ArgumentOutOfRangeException : Index and count must refer to a location within the buffer.
Parameter name: chars</Message>
          <StackTrace>   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Pocket.CompositeDisposable.Dispose() in /home/tyoverby/.nuget/packages/pocket.disposable/1.0.3/contentFiles/cs/any/(Pocket)/Disposable.cs:line 69
   at Pocket.For.Xunit.TestLog.Dispose() in /home/tyoverby/.nuget/packages/pocketlogger.for.xunit/0.1.3/contentFiles/cs/any/(Pocket)/Logger/For.Xunit/TestLog.cs:line 89
   at Pocket.For.Xunit.LogToPocketLoggerAttribute.After(MethodInfo methodUnderTest) in /home/tyoverby/.nuget/packages/pocketlogger.for.xunit/0.1.3/contentFiles/cs/any/(Pocket)/Logger/For.Xunit/LogToPocketLoggerAttribute.cs:line 38</StackTrace>
```

**Comment by jonsequitur** [comment]
I've simplified the file writing which I believe resolves this: #73
